### ISSUE TITLE
3.3.1. Como usuario puedo ingresar al modulo llamado 'La Ley de los Tres Pasos'

### ISSUE THREAD

**Issue by JPPINZONR** [JPPINZONR/HiddenMemory#66]

**Comment by JPPINZONR** [comment]
Criterios de aceptación:

- [x] Visualizar al seleccionar la opción en el menú el modulo 'La Ley de los Tres Pasos'
- [ ] Seleccionar el modulo  'La Ley de los Tres Pasos'.
- [x] Por defecto el juego seleccionara el modulo 'La Ley de los Tres Pasos' para que se pueda iniciar el juego.
- [ ]  Visualizar el nombre del modulo en color verde junto con un visto bueno, cuando el jugador  complete el modulo.

**Comment by Johanhts** [comment]
Se realiza tarea
